### ISSUE TITLE
Messages are infinitely reusable, have no time limit, and cannot be cancelled

### ISSUE THREAD

**Issue by BrendanChou** [makerdao/median#4]
A signer can sign a message with a future timestamp, and then once that message is public, it is infinitely submittable to the contract without being able to cancel that message or override it (prevent it from being submittable) without `drop`ing the signer.

The most likely issue that this would cause is:
 - The signers sign some price data that is valid for some amount of time into the future (say 1 hour)
- This data is submitted on-chain (TX1) and is now public for everyone to re-use (since the saved `age` is simply the `block.timestamp` and not related to the timestamp of the signed message)
- The price swings quickly and all signers re-sign some price data for another hour into the future.
- This new data is submitted on-chain (TX2) and changes the feed data
- Anyone (since poke is external with no auth) can resubmit the same data as TX1 to change the price back to its previous value as long as the message age is still valid

**Comment by nanexcool** [comment]
Yeah, this is true. If someone signs a message with timestamp +100 year, that message will be valid forever unless we drop the signer.

One thing we thought about was having an increasing nonce in the Median, but that means that price signers need to be aware of the blockchain state which is something we wanted to avoid.

Do you have any suggestions?

**Comment by nanexcool** [comment]
Maybe something like, price has to be greater than last but lower than some threshold?

**Comment by BrendanChou** [comment]
Ah I see now the messages need to just be greater than the timestamp of the last update, not greater than the timestamp of the current update. So people don't have to sign messages for an hour in the future.

So really the only problem is people signing messages for far in the future. Since most nodes will reject block timestamps that are too far off, it may be worth preventing messages that are signed for more than X minutes into the future?

Another possibility is allowing signers to explicitly cancel messages for certain timestamps?

Anyway I'm kind of realizing this is a non-issue especially if the number of signers is greater than 3. The whole point of the median is to be resilient against one address being malicious or messing up their messages. I'll let you close this if you also feel this is a relative non-issue
